### ISSUE TITLE
Extend storage handler response - add media_type field

### ISSUE THREAD

**Issue by artemmufazalov** [ydb-platform/ydb-embedded-ui#647]
Currently v2 storage response contains long full disk types

They should be converted to `HDD`, `SSD` if this substrings are present

![Image](https://github.com/ydb-platform/ydb-embedded-ui/assets/67755036/877380b3-5bc4-423f-8a98-1b429b134ec0)

Let's use type property
```
      storage_pool_types:
      - kind: /Root:ssd_1
        pool_config:
          box_id: '1'
          erasure_species: block-4-2
          kind: /Root:ssd_1
          pdisk_filter:
          - property:
            - type: SSD
```
